### PR TITLE
Implement std::error::Error

### PR DESCRIPTION
**Pull request by ahihi**
Because `Box<Error>` is nice for prototyping :-)

### CODE REVIEW

**Comment by klingtnet** [comment]
Hi,
can you elaborate in a bit more detail what the purpose of this PR is?
The description string for port-midi errors is provided by [this function](https://github.com/ahihi/portmidi-rs/blob/871b00a1d7be4e39e989d14b25cf2c0963fc4dcf/src/ffi/types.rs#L76).
Please use this instead of the self written error strings.

**Comment by ahihi** [comment]
Hello,

The purpose is just to add an implementation for the standard Error trait. Unfortunately its description() method is not designed to be very dynamic and must return &str, so I think it is not possible to use the error text functions here.

**Comment by klingtnet** [comment]
I think you're right, we cant use the error text function because of the `&str` returned type, like you already said. Can you replace the static error messages with those from [portmidi.c](http://portmedia.sourceforge.net/portmidi/doxygen/portmidi_8c-source.html)?

**Comment by ahihi** [comment]
Good idea, done.

**Comment by musitdev** [comment]
Just a question before merge. Why not call Pm_GetErrorText for portmidi errors to get the text instead of copy / cut?

**Comment by klingtnet** [comment]
The [`std::error::Error`](https://doc.rust-lang.org/std/error/trait.Error.html) trait defines that the `description` method must return a `&str` and we can't convert a dynamically allocated `String` to `&str` /wo introducing lifetimes.
Please correct me if I'm wrong.

**Comment by klingtnet** [comment]
We can refactor our `Error` type later, therefore it's safe to merge the PR.

**Comment by musitdev** [comment]
Ok I understand. I think you can if you keep the reference to the string inside the error and return the reference to it. The string will be free with the error. Perhaps If I find the time I'll give it a try.
I'll do the merge and the release.

**Comment by klingtnet** [comment]
@musitdev This should work, great idea!

**Pull request merged**
